name: Flatpak CI Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Flatpak Build Environnement
        run: sudo apt-get update && sudo apt install flatpak flatpak-builder
      - name: Install Kde sdk
        run: sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo && (yes | sudo flatpak install flathub org.kde.Sdk//6.2)
      - name: Build Release
        run: sudo flatpak-builder --user --install --force-clean build-dir org.gnuradio.Companion
