name: Flatpak CI Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Flatpak Build Environnement
        run: sudo apt-get update && sudo apt install flatpak flatpak-builder
      

